# Generated by Django 2.0.5 on 2018-05-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0002_auto_20180524_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='type',
            field=models.CharField(default='expense', max_length=40),
        ),
    ]
