# Generated by Django 2.1 on 2018-08-12 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0003_entry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='robertinho', max_length=255)),
                ('telegram_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(default=234467217, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='telebot.User'),
            preserve_default=False,
        ),
    ]
